config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "budgets#index"

  resources :budgets
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.human_enum_name(enum_name, enum_value)
    I18n.t("activerecord.enums.#{model_name.i18n_key}.#{enum_name}.#{enum_value}")
  end

  def self.enum_collection_for_select(enum_name, ignore: [])
    ignore = ignore.class == Array ? ignore : [ignore]
    ignore.map!(&:to_s)
    self.send(enum_name.to_s.pluralize).map do |enum_key, enum_value|
      next if ignore.include?(enum_key)
      [human_enum_name(enum_name, enum_key), enum_key]
    end.compact
  end
end

app/models/budget.rb
class Budget < ApplicationRecord
  has_many :incomes, dependent: :destroy
  has_many :expenses, dependent: :destroy

  accepts_nested_attributes_for :incomes, allow_destroy: true
  accepts_nested_attributes_for :expenses, allow_destroy: true

  validates :description, presence: true
  validates :value, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :budget

  validates :description, presence: true
  validates :value, presence: true
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :budget

  validates :description, presence: true
  validates :value, presence: true
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :budget

  validates :description, presence: true
  validates :value, presence: true

  enum kind: { income: 1, expenses: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :budgets

  validates :full_name, presence: true

  enum role: { user: 1, administrator: 2 }

  def custom_name(amount = 1)
    full_name.split.take(amount).join(" ")
  end

  def role_humanize
    User.human_enum_name(:role, role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  layout :layout_by_resource

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:full_name, :email, :password, :password_confirmation)
    end
  end

  private
    def layout_by_resource
      devise_controller? ? "devise" : "application"
    end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: %i[ edit update destroy ]

  def index
    @search = params[:search].to_s.strip
    @budgets = current_user.budgets
    @budgets = @budgets.where('description LIKE :s ', s: "%#{@search}%") unless @search.blank?

    respond_to do |format|
      if request.xhr?
        format.html { render partial: 'list', locals: { budgets: @budgets, search: @search } }
      else
        format.html
      end
    end
  end

  def new
    @budget = Budget.new
    @budget.incomes.build
    @budget.expenses.build

    respond_to do |format|
      format.html { render partial: 'form', locals: { budget: @budget } }
    end
  end

  def create
    @budget = Budget.new(budget_params.merge(user_id: current_user.id))
    respond_to do |format|
      if @budget.save
        format.html { redirect_to budgets_path, notice: 'El presupuesto fue creado exitosamente.' }
      else
        ap "xxxx"
        ap @budget.errors
        ap "xxxx"
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    respond_to do |format|
      format.html { render partial: 'form', locals: { budget: @budget } }
    end
  end

  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to budgets_path, notice: 'El presupuesto fue actualizado exitosamente.' }
      else
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @budget.destroy

    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'El presupuesto fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private

    def set_budget
      @budget = Budget.find(params[:id])
    end

    def budget_params
      params.require(:budget).permit(
        :description,
        :value,
        incomes_attributes: [:id, :description, :value, :_destroy],
        expenses_attributes: [:id, :description, :value, :_destroy]
      )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  before_action :user_can_access?, only: [:edit, :update]

  def edit
    respond_to do |format|
      format.html { render partial: 'form_modal', locals: { user: @user } }
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_back fallback_location: root_path, notice: 'Sus datos se actualizaron correctamente.' }
      else
        format.html { render partial: 'form', locals: { user: @user }, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      fields = params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
      if fields[:password].blank?
        fields.delete(:password)
        fields.delete(:password_confirmation)
      end

      fields
    end

    def user_can_access?
      if current_user.id != @user.id
        render partial: 'shared/errors/inaccessible'
        return
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/budgets/_budget.html.erb
<div class="row mb-1">
  <div class="col-9">
    <div class="d-flex flex-column">
      <span class="font-weight-bold"><%= budget.description %></span>
      <span class="text-muted text-truncate">S/ <%= budget.value %></span>
    </div>
  </div>
  <div class="col-3">
    <div class="row justify-content-center">
      <%= link_to edit_budget_path(budget), data: { action: " ajax:success->budgets#renderForm ajax:success->budgets#initialConfigForm" }, remote: true do %>
        <%= image_tag('icon-edit.svg') %>
      <% end %>
      <%= link_to budget_path(budget), method: :delete, data: { confirm: "Seguro de eliminar presupuesto?" }, class: "pl-1" do %>
        <%= image_tag('icon-delete.svg') %>
      <% end %>
    </div>
  </div>
</div>

app/views/budgets/_expense_fields.html.erb
<div class="row align-items-center p-1 form-expense">
  <div class="col-7">
    <%= form.text_field :description, class: "form-control expense_description", placeholder: "Ingresar Descripción", required: true %>
  </div>
  <div class="col-3">
    <%= form.number_field :value, step: :any, class: "form-control expense_value", required: true, min: 0, data: {
      action: "change->budgets#loadAvailableBudget"
    } %>
  </div>
  <div class="col-2">
    <%= form.hidden_field :_destroy %>
    <%= link_to "#", class: "text-danger", data: {
      action: "click->budgets#removeItem click->budgets#loadAvailableBudget",
      model: {
        class: ".form-expense",
        name: "egresos",
        class_attributes: {
          description: ".expense_description",
          value: ".expense_value"
        }
      }
    } do %>
      <%= image_tag('icon-delete.svg') %>
    <% end %>
  </div>
</div>

app/views/budgets/_form.html.erb
<%= form_with(model: budget, remote: true) do |form| %>
  <div class="card rounded-sm">
    <div class="card-header bg-dark">
      <div class="presupuesto">
        <div class="presupuesto_titulo">Presupuesto Disponible</div>
        <%= form.text_field :description, class: "form-control text-center presupuesto_descripcion", required: true, placeholder: "Agregar descripción" %>
        <%= form.hidden_field :value, class: "form-control", data: {
          budgets_target: "budgetValue"
        } %>
        <div class="presupuesto_valor" id="presupuesto"></div>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-xl-4 col-lg-6 col-md-8">
              <div class="presupuesto_ingreso limpiarEstilos">
                <div class="presupuesto_ingreso--texto">Ingresos</div>
                <div class="derecha limpiarEstilos">
                  <div class="presupuesto_ingreso--valor" id="ingresos"></div>
                  <div class="presupuesto_ingreso--porcentaje">&nbsp;</div>
                </div>
              </div>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col-xl-4 col-lg-6 col-md-8">
              <div class="presupuesto_egreso limpiarEstilos">
                <div class="presupuesto_egreso--texto">Egresos</div>
                <div class="derecha limpiarEstilos">
                  <div class="presupuesto_egreso--valor" id="egresos"></div>
                  <div class="presupuesto_egreso--porcentaje" id="porcentaje"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
      <template data-budgets-target="templateIncome">
        <%= form.fields_for :incomes, Income.new, child_index: "TEMPLATE_RECORD" do |income| %>
          <%= render "income_fields", form: income %>
        <% end %>
      </template>
      <template data-budgets-target="templateExpense">
        <%= form.fields_for :expenses, Expense.new, child_index: "TEMPLATE_RECORD" do |expense| %>
          <%= render "expense_fields", form: expense %>
        <% end %>
      </template>

      <div class="row">
        <div class="col-sm-12 col-lg-2">
          <div class="row">
            <div class="col-6 col-lg-12 p-1"><%= link_to "Cancelar", budgets_path, class: "btn btn-light font-weight-bold w-100", data: { action: "click->budgets#cancelForm" } %></div>
            <div class="col-6 col-lg-12 p-1"><%= form.submit "Guardar", class: "btn btn-success font-weight-bold w-100" %></div>
            <div class="col-6 col-lg-12 p-1">
              <%= link_to "Añadir Ingreso", "#", class: "btn btn-ingreso font-weight-bold w-100", data: {
                action: "click->budgets#addItem",
                list_target: "incomeListTarget",
                template_target: "templateIncomeTarget"
              } %>
            </div>
            <div class="col-6 col-lg-12 p-1">
              <%= link_to "Añadir Egreso", "#", class: "btn btn-danger font-weight-bold w-100", data: {
                action: "click->budgets#addItem",
                list_target: "expenseListTarget",
                template_target: "templateExpenseTarget"
              } %>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-lg-5 mt-3 mt-sm-0">
          <h2 class="ingreso_titulo">Ingresos</h2>
          <div data-budgets-target="incomeList">
            <%= form.fields_for :incomes do |income| %>
              <%= render "income_fields", form: income %>
            <% end %>
          </div>
        </div>
        <div class="col-sm-6 col-lg-5 mt-3 mt-sm-0">
          <h2 class="egreso_titulo">Egresos</h2>
          <div data-budgets-target="expenseList">
            <%= form.fields_for :expenses do |expense| %>
              <%= render "expense_fields", form: expense %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/budgets/_income_fields.html.erb
<div class="row align-items-center p-1 form-income">
  <div class="col-7">
    <%= form.text_field :description, class: "form-control income_description", placeholder: "Ingresar Descripción", required: true %>
  </div>
  <div class="col-3">
    <%= form.number_field :value, step: :any, class: "form-control income_value", required: true, min: 0, data: {
      action: "change->budgets#loadAvailableBudget"
    } %>
  </div>
  <div class="col-2">
    <%= form.hidden_field :_destroy %>
    <%= link_to "#", class: "text-danger", data: {
      action: "click->budgets#removeItem click->budgets#loadAvailableBudget",
      model: {
        class: ".form-income",
        name: "ingresos",
        class_attributes: {
          description: ".income_description",
          value: ".income_value"
        }
      }
    } do %>
      <%= image_tag('icon-delete.svg') %>
    <% end %>
  </div>
</div>

app/views/budgets/_list.html.erb
<div class="card">
  <div class="card-header bg-white border-bottom font-weight-bold">Presupuestos</div>
  <div class="card-body">
    <ul class="list-group">
      <%= render budgets %>
      <% if budgets.empty? %>
        <li class="d-flex align-items-center">
          <% if search.blank? %>
            No hay registros.
          <% else %>
            No hay coincidencias.
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/budgets/index.html.erb
<div data-controller="budgets">
  <div class="row">
    <div class="col-md-4 mb-3 mb-md-0">
      <div class="search-box">
        <%= form_tag(budgets_path, method: :get, remote: true, data: { action: "ajax:success->budgets#renderList" }) do %>
          <div class="position-relative">
            <input type="search" name="search" class="form-control rounded-sm"
                    placeholder="Buscar..."
                    value="<%= @search %>">
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-8">
      <%= link_to "Agregar", new_budget_path, class: "btn btn-success", remote: true, data: {
        action: "
          ajax:success->budgets#renderForm
          ajax:success->budgets#initialConfigForm
        "
      } %>
    </div>
  </div>
  <div class="row mb-4">
    <div class="col-xl-4 mt-4" data-budgets-target="listContainer">
      <%= render "list", budgets: @budgets, search: @search %>
    </div>
    <div class="col-xl-8 mt-4" data-budgets-target="formContainer"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Presupuesto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-controller="app">
    <%= render 'layouts/application/navigation' %>

    <div class="main-content">
      <div class="page-content">
        <div class="container-fluid">
          <%= render 'shared/flash_message' %>

          <%= yield %>
        </div>
      </div>
    </div>

    <%= render 'layouts/application/components' %>
  </body>
</html>

app/views/layouts/application/_components.html.erb
<!-- Modal -->
<div class="modal fade" tabindex="-1" aria-hidden="true" style="display: none;"
        data-controller="modal"
        data-app-target="modal"
        data-keyboard="false"
        data-backdrop="static">
  <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable" data-modal-target="content"></div>
</div>

app/views/layouts/application/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <a class="navbar-brand" href="<%= root_path %>">Presupuestos</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-lg-auto">
      <li class="nav-item">
        <%= link_to "Ver perfil", edit_user_path(current_user), class: "nav-link", data: { action:"click->app#launchModal" } %>
      </li>
    </ul>
    <div class="my-2 my-lg-0 ml-0 ml-lg-3">
      <%= link_to destroy_user_session_path, class: "text-danger", data: { method: :delete } do %>
        <i class="fas fa-power-off text-danger"></i>
        Cerrar Sesión
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Iniciar Sesión</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "login", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="login-card">
      <%= render "shared/flash_message" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash_message.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= notice.html_safe %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert.html_safe %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, remote: true, data: { controller: "form", action: "ajax:error->form#replace" }) do |form| %>
  <%= render "shared/errors/form_errors", resource: user %>

  <div class="row mb-3">
    <div class="col-md-4 align-self-center">
      <%= form.label :full_name, class: "font-weight-bold mb-0" %>
    </div>
    <div class="col-md-8">
      <%= form.text_field :full_name, class: "form-control", required: true %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-md-4 align-self-center">
      <%= form.label :email, class: "font-weight-bold mb-0" %>
    </div>
    <div class="col-md-8">
      <%= form.email_field :email, class: "form-control", required: true %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-md-4 align-self-center">
      <%= form.label :password, class: "font-weight-bold mb-0" %>
    </div>
    <div class="col-md-8">
      <%= form.password_field :password, class: "form-control" %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-md-4 align-self-center">
      <%= form.label :password_confirmation, class: "font-weight-bold mb-0" %>
    </div>
    <div class="col-md-8">
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>

  <div class="d-flex">
    <button type="button" class="btn btn-light ml-auto" data-action="click->modal#close">Cerrar</button>
    <%= form.submit "Guardar", class: "btn btn-success ml-3" %>
  </div>
<% end %>

app/views/users/_form_modal.html.erb
<div class="modal-content">
  <div class="modal-header">
    <h4 class="my-0">Actualizar datos</h4>
  </div>
  <div class="modal-body">
    <%= render 'form', user: user %>
  </div>
</div>